version: '3.5'
services:
  coredns:
    image: "coredns/coredns:1.2.0"
    labels:
      dev.local.description: "localdns"
    volumes:
    - ./dns:/opt/coredns
    ports:
    - target: 2053
      published: 2053
      protocol: udp
      mode: host
    - target: 2053
      published: 2053
      protocol: tcp
      mode: host
    entrypoint:
    - /coredns
    - -conf
    - /opt/coredns/Corefile
